server {
    listen 80;

    # Sirve los archivos estáticos del build
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy hacia el backend privado
    location /api/ {
        proxy_pass http://10.0.144.74:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}