server {
    listen 80;

    # Sirve los archivos estáticos del build
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Necesario para React Router
        try_files $uri $uri/ /index.html;
    }
}