name: CI/CD Deploy ECS

on:
  push:
    branches:
      - deploy

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login a ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build y push imagen backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.ECR_REGISTRY }}/innovatech-backend:latest

      - name: Deploy backend en ECS
        run: |
          aws ecs update-service \
            --cluster innovatech-cluster \
            --service backend-service \
            --force-new-deployment \
            --region us-east-1

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login a ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build y push imagen frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.ECR_REGISTRY }}/innovatech-frontend:latest
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}

      - name: Deploy frontend en ECS
        run: |
          aws ecs update-service \
            --cluster innovatech-cluster \
            --service innovatech-frontend-service-8tcy5j81 \
            --force-new-deployment \
            --region us-east-1
